### ISSUE TITLE
About the different dialects of Chinese 

### ISSUE THREAD

**Issue by ZhangYiJiang** [erikbern/lang-pitch#1]
Hi! I found your blog post on language pitches really interesting. A note about Chinese from a native speaker - the different variants of Chinese are not really dialects so much as mutually unintelligible languages that happen to have very similar vocabulary and grammar. It's probably best not to group them together when analyzing them. 

Wikipedia explains it much better than I can ever hope to, so I'll just link it here: https://en.wikipedia.org/wiki/Varieties_of_Chinese. Geographical areas as small as a cities can have dialects that are difficult or impossible to understand to outsiders, and there are also accent differences not unlike the difference between American and British English. Here's a short YouTube video with clips from several of them. The first clip has two Mandarin speakers with different accents, which is also interesting to listen to https://www.youtube.com/watch?v=znmgQ-C9zTo (they are also talking *about* accents, comparing the host's accent to the guest's Beijing accent).

**Comment by erikbern** [comment]
yeah – i'm aware of that, and if you look at my stats i actually separate them out as different languages (wu, mandarin, etc)
